(function(){
if(window.__nexoFichasApp)return;window.__nexoFichasApp=true;
const CSS='https://dtokurisu-png.github.io/nexo-inventory-smart/nexo-core/fichas-ui.css?v=20260926-1';
const API='/_functions/nexoFichasUi';
let sessionToken='',boot=null,activeTab='collections',search='',selectedSheet=null,bootstrap=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>Number.isFinite(Number(v))?'$'+Number(v).toFixed(2):'—';
const pct=v=>Number.isFinite(Number(v))?Number(v).toFixed(1)+'%':'—';
function addCss(){if(document.getElementById('nx-fichas-css'))return;const l=document.createElement('link');l.id='nx-fichas-css';l.rel='stylesheet';l.href=CSS;document.head.appendChild(l)}
function mount(){addCss();document.body.classList.add('nx-fichas-lock');let r=document.getElementById('nx-fichas-app');if(!r){r=document.createElement('div');r.id='nx-fichas-app';r.className='nx-fichas-app';document.body.appendChild(r)}return r}
function html(v){mount().innerHTML=v}
function loading(t='Preparando Fichas Técnicas…'){html('<div class="nx-loading"><div><div class="nx-spinner"></div><strong>'+esc(t)+'</strong><p style="color:#93a0b4">Conectando con tu espacio Nexo.</p></div></div>')}
function toast(t){let x=document.querySelector('.nx-toast');if(x)x.remove();x=document.createElement('div');x.className='nx-toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),3200)}
function err(e){const m=String(e&&e.message?e.message:e||'Error');html('<div class="nx-loading"><div class="nx-error"><h2>No se pudo abrir Fichas Técnicas</h2><p>'+esc(m)+'</p><button class="nx-btn nx-btn-accent" id="nx-retry">Reintentar</button></div></div>');document.getElementById('nx-retry')?.addEventListener('click',()=>location.reload())}
async function api(action,payload={}){const h={'Content-Type':'application/json','Accept':'application/json'};if(sessionToken)h.Authorization='Bearer '+sessionToken;const r=await fetch(API,{method:'POST',cache:'no-store',headers:h,body:JSON.stringify({action,...payload})});let d={};try{d=await r.json()}catch(_){throw new Error('Respuesta inválida del servidor')}if(!r.ok||d.ok===false)throw new Error(d.error||'Operación no disponible');return d.data??d}
function bootToken(){return new URLSearchParams(location.search).get('nxb')||''}
function stripBoot(){try{const u=new URL(location.href);u.searchParams.delete('nxb');history.replaceState(history.state||{},'',u.pathname+(u.search||'')+(u.hash||''))}catch(_){}}
async function waitBoot(){for(let i=0;i<160;i++){const t=bootToken();if(t)return t;await new Promise(r=>setTimeout(r,75))}throw new Error('No se recibió una sesión segura. Recarga la página.')}
async function start(){loading();const b=await waitBoot();const ex=await api('exchange',{bootToken:b});sessionToken=ex.sessionToken||'';stripBoot();bootstrap=await api('bootstrap');renderHome()}
function ctxLabel(){const c=bootstrap?.context||{};return c.type==='workspace'?(c.workspaceName||'Workspace'):'Mi espacio'}
function visibleSheets(){let list=[...(bootstrap?.sheets||[])];if(search){const q=search.toLowerCase();list=list.filter(x=>((x.titleEs||'')+' '+(x.titleEn||'')+' '+(x.category||'')).toLowerCase().includes(q))}return list}
function collectionSheets(c){const ids=new Set(c.sheetIds||[]);return visibleSheets().filter(s=>ids.has(s.id))}
function top(){return '<div class="nx-top"><div class="nx-brand"><div class="nx-logo">N</div><div class="nx-title"><h1>Fichas Técnicas Dinámicas</h1><p>NEXO / '+esc(ctxLabel())+'</p></div></div><div class="nx-actions"><span class="nx-badge">'+esc(bootstrap?.context?.roleKey||'owner')+'</span>'+(bootstrap?.capabilities?.canEdit?'<button class="nx-btn nx-btn-accent" id="nx-new-col">Nueva colección</button>':'')+'</div></div>'}
function renderHome(){selectedSheet=null;const cols=bootstrap?.collections||[];const sheets=visibleSheets();const body=activeTab==='collections'?renderCollections(cols):renderSheets(sheets);html('<div class="nx-shell">'+top()+'<main class="nx-main"><div class="nx-toolbar"><div class="nx-tabs"><button class="nx-tab '+(activeTab==='collections'?'active':'')+'" data-tab="collections">Colecciones</button><button class="nx-tab '+(activeTab==='sheets'?'active':'')+'" data-tab="sheets">Fichas técnicas</button></div><input id="nx-search" class="nx-search" placeholder="Buscar fichas…" value="'+esc(search)+'"></div>'+body+'</main></div>');bindHome()}
function renderCollections(cols){if(!cols.length)return '<div class="nx-empty">Todavía no tienes colecciones disponibles.</div>';return '<div class="nx-grid">'+cols.map(c=>'<article class="nx-card" data-col="'+esc(c.id)+'"><h3>'+esc(c.name)+'</h3><p>'+esc(c.description||'Colección de fichas técnicas')+'</p><div class="nx-card-meta"><span>'+((c.sheetIds||[]).length)+' fichas</span><span>'+esc(c.sourceKey||'personal')+'</span></div></article>').join('')+'</div>'}
function renderSheets(list){if(!list.length)return '<div class="nx-empty">No hay fichas que coincidan con la búsqueda.</div>';return '<div class="nx-list">'+list.map(s=>'<article class="nx-row" data-sheet="'+esc(s.id)+'"><div><h3>'+esc(s.titleEs||s.titleEn||s.id)+'</h3><p>'+esc(s.titleEn&&s.titleEs?s.titleEn:(s.category||s.recipeType||''))+'</p></div><span class="nx-pill">'+esc(s.recipeType||'Ficha')+'</span></article>').join('')+'</div>'}
function bindHome(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;renderHome()});const q=document.getElementById('nx-search');if(q)q.oninput=()=>{search=q.value||'';renderHome()};document.querySelectorAll('[data-sheet]').forEach(x=>x.onclick=()=>openSheet(x.dataset.sheet));document.querySelectorAll('[data-col]').forEach(x=>x.onclick=()=>openCollection(x.dataset.col));document.getElementById('nx-new-col')?.addEventListener('click',newCollection)}
function openCollection(id){const c=(bootstrap?.collections||[]).find(x=>x.id===id);if(!c)return;const list=collectionSheets(c);html('<div class="nx-shell">'+top()+'<main class="nx-main"><div class="nx-toolbar"><button class="nx-btn" id="nx-back">← Colecciones</button><div><strong>'+esc(c.name)+'</strong><div style="color:#93a0b4;font-size:12px;margin-top:3px">'+list.length+' fichas</div></div></div>'+renderSheets(list)+'</main></div>');document.getElementById('nx-back').onclick=renderHome;document.querySelectorAll('[data-sheet]').forEach(x=>x.onclick=()=>openSheet(x.dataset.sheet))}
async function openSheet(id){try{loading('Abriendo ficha…');selectedSheet=await api('sheet',{sheetId:id});renderSheet()}catch(e){err(e)}}
function renderSheet(){const d=selectedSheet,s=d.sheet||{},sections=d.sections||[],comps=d.components||[],canCost=d.capabilities?.canViewCosts;const bySec=new Map;comps.forEach(c=>{if(!bySec.has(c.sectionId))bySec.set(c.sectionId,[]);bySec.get(c.sectionId).push(c)});const details=sections.map(sec=>'<div><div class="nx-section-title">'+esc(sec.titleEs||sec.titleEn||'Sección')+'</div>'+(bySec.get(sec.id)||[]).map(c=>'<div class="nx-component"><div><strong>'+esc(c.displayEs||c.displayEn||c.targetIngredientId||c.targetRecipeId||'Componente')+'</strong><small>'+esc(c.noteEs||c.noteEn||'')+'</small></div><span class="nx-qty">'+esc(c.quantity??'')+' '+esc(c.unitEs||c.unitEn||'')+'</span></div>').join('')+'</div>').join('');html('<div class="nx-shell">'+top()+'<main class="nx-main"><div class="nx-toolbar"><button class="nx-btn" id="nx-back">← Biblioteca</button><div class="nx-actions">'+(canCost?'<button class="nx-btn" id="nx-links">Vincular Inventory Smart</button><button class="nx-btn nx-btn-accent" id="nx-cost">Ver costos</button>':'')+'</div></div><div class="nx-sheet"><section class="nx-panel"><div class="nx-sheet-head"><div><h2>'+esc(s.titleEs||s.titleEn||s.id)+'</h2><p>'+esc(s.titleEn&&s.titleEs?s.titleEn:'')+'</p></div><span class="nx-pill">'+esc(s.recipeType||'Ficha')+'</span></div>'+details+'</section><aside class="nx-panel"><strong>Rendimiento</strong><div style="margin:10px 0 20px;font-size:22px;font-weight:800">'+esc(s.yieldQty??'—')+' '+esc(s.yieldUnitEs||s.yieldUnitEn||'')+'</div><strong>Método</strong><p style="color:#b2bdcd;white-space:pre-wrap;font-size:13px;line-height:1.55">'+esc(d.sheet?.methodEs||d.sheet?.methodEn||'Sin método registrado.')+'</p></aside></div></main></div>');document.getElementById('nx-back').onclick=renderHome;document.getElementById('nx-links')?.addEventListener('click',openLinks);document.getElementById('nx-cost')?.addEventListener('click',openCost)}
async function newCollection(){const name=prompt('Nombre de la colección');if(!name)return;try{await api('collection.create',{input:{name}});bootstrap=await api('bootstrap');toast('Colección creada');renderHome()}catch(e){toast(e.message||String(e))}}
async function openLinks(){try{const d=await api('inventory.candidates',{sheetId:selectedSheet.sheet.id});const rows=d.rows||[];const body=rows.length?rows.map(r=>{const opts=(r.exactCandidates||[]).map(x=>'<option value="'+esc(x.id)+'" '+(r.currentLink?.inventoryItemId===x.id?'selected':'')+'>'+esc(x.productName)+' · '+esc(x.supplier||'')+' · '+esc(x.costPerUnit??'—')+'/'+esc(x.unidadCosto||'')+'</option>').join('');return '<div class="nx-link-row"><div><h4>'+esc(r.displayEs||r.displayEn||r.ingredientId)+'</h4><p>'+esc(r.quantity??'')+' '+esc(r.unit||'')+(r.ambiguousExactMatch?' · coincidencia ambigua':'')+'</p></div><div><select class="nx-select" data-link-component="'+esc(r.componentId)+'" data-ing="'+esc(r.ingredientId)+'"><option value="">Sin vínculo</option>'+opts+'</select></div></div>'}).join(''):'<div class="nx-empty">No hay componentes vinculables en esta ficha.</div>';modal('Vincular con Inventory Smart',body);document.querySelectorAll('[data-link-component]').forEach(sel=>sel.onchange=async()=>{try{if(sel.value){await api('inventory.link',{input:{technicalSheetId:selectedSheet.sheet.id,componentId:sel.dataset.linkComponent,inventoryItemId:sel.value,linkScope:'ingredient',matchMethod:'manual'}})}else{await api('inventory.unlink',{input:{technicalSheetId:selectedSheet.sheet.id,componentId:sel.dataset.linkComponent,linkScope:'ingredient'}})}toast('Vínculo actualizado')}catch(e){toast(e.message||String(e))}})}catch(e){toast(e.message||String(e))}}
async function openCost(){try{const c=await api('cost',{sheetId:selectedSheet.sheet.id});const rows=(c.components||[]).map(x=>'<div class="nx-cost-row"><div class="nx-cost-row-top"><span>'+esc(x.label||x.componentId)+'</span><strong>'+money(x.knownCost)+'</strong></div><div class="nx-bar"><span style="width:'+Math.max(0,Math.min(100,Number(x.contributionPercent)||0))+'%"></span></div><div style="margin-top:5px;color:#93a0b4;font-size:11px">'+(x.status==='COSTED'?pct(x.contributionPercent):'<span class="nx-warn">'+esc(x.reason||x.status)+'</span>')+'</div></div>').join('');const body='<div class="nx-cost-total">'+money(c.totalKnownCost)+'</div><div class="nx-cost-sub">Costo conocido'+(c.complete?' · completo':' · '+c.unresolvedCount+' pendientes')+(c.costPerYieldUnit!=null?' · '+money(c.costPerYieldUnit)+' por unidad de rendimiento':'')+'</div><div style="margin-top:18px">'+rows+'</div>';modal('Costos de la ficha',body)}catch(e){toast(e.message||String(e))}}
function modal(title,body){const o=document.createElement('div');o.className='nx-overlay';o.innerHTML='<div class="nx-modal"><div class="nx-modal-head"><strong>'+esc(title)+'</strong><button class="nx-btn" data-close>✕</button></div><div class="nx-modal-body">'+body+'</div></div>';document.body.appendChild(o);o.querySelector('[data-close]').onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()}}
start().catch(err);
})();