(()=>{'use strict';
if(window.__NEXO_TAXONOMY_V3__)return;window.__NEXO_TAXONOMY_V3__=true;
const DATA=window.__NEXO_DM_DATA__||{recipes:[],ingredients:[],preparations:[]};
const view=document.getElementById('view'),back=document.getElementById('back'),home=document.getElementById('home'),modal=document.getElementById('modal');
if(!view||!back||!home||!modal)return;
const state={mode:'root',nativeCards:{dish:[],prep:[]},productModal:false,applying:false};
const style=document.createElement('style');style.id='nexo-taxonomy-v3-style';style.textContent=`
.recipeCard:before{display:none!important}.recipeCard{appearance:none!important;-webkit-appearance:none!important;position:relative!important;border-top:1px solid var(--line)!important}.recipeCard:after{content:"";position:absolute;z-index:4;left:0;right:0;bottom:0;height:9px;background:var(--product)}.recipeCard.cardDish:after{background:var(--dish)}.recipeCard.cardPrep:after{background:var(--prep)}.recipeCard.cardProduct:after{background:var(--product)}.recipeCard .meta{padding-bottom:22px!important}
.taxonomyHome,.taxonomyCategory{padding:0}.taxonomyIntro{margin-bottom:18px}.taxonomyGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.taxonomyMaster{appearance:none;-webkit-appearance:none;position:relative;min-height:210px;border:1px solid var(--line);border-radius:18px;background:var(--panel);overflow:hidden;text-align:left;padding:24px 22px 28px;box-shadow:0 8px 24px rgba(25,20,14,.06);color:var(--ink)}.taxonomyMaster:after{content:"";position:absolute;left:0;right:0;bottom:0;height:11px}.taxonomyMaster.dish:after{background:var(--dish)}.taxonomyMaster.prep:after{background:var(--prep)}.taxonomyMaster.product:after{background:var(--product)}.taxonomyMaster .taxonomyLabel{display:inline-flex;padding:5px 9px;border:1px solid currentColor;border-radius:999px;font-size:11px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.taxonomyMaster.dish .taxonomyLabel{color:var(--dish)}.taxonomyMaster.prep .taxonomyLabel{color:var(--prep)}.taxonomyMaster.product .taxonomyLabel{color:var(--product)}.taxonomyMaster h2{margin:34px 0 6px;font-size:30px;letter-spacing:-.035em}.taxonomyMaster p{margin:0;color:var(--muted)}.taxonomyCount{position:absolute;right:20px;top:20px;display:grid;place-items:center;min-width:42px;height:42px;padding:0 10px;border-radius:999px;background:var(--bg);font-weight:900}.taxonomyCategoryHead{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:12px}.taxonomyCategoryHead h1{margin:0;font-size:clamp(30px,5vw,46px);letter-spacing:-.035em}.taxonomyCategoryHead p{margin:5px 0 0;color:var(--muted)}.taxonomyCategory .search{margin-bottom:15px}.taxonomyBackHint{border:1px solid var(--line);background:#fff;border-radius:12px;padding:9px 12px;font-weight:800}
.taxonomyProductCard[data-product-id]{cursor:zoom-in}.taxonomyProductCard.taxonomyNoPhoto{cursor:default}.taxonomyProductCard.taxonomyNoPhoto:focus{outline:none}.taxonomyImageShade{position:fixed;z-index:180;inset:0;background:rgba(12,11,9,.88);display:grid;place-items:center;padding:24px}.taxonomyImageViewer{position:relative;display:flex;align-items:center;justify-content:center;width:min(1100px,96vw);height:min(900px,92dvh)}.taxonomyImageViewer img{display:block;max-width:100%;max-height:100%;width:auto;height:auto;object-fit:contain;border-radius:18px;box-shadow:0 24px 80px rgba(0,0,0,.38)}.taxonomyImageClose{position:absolute;z-index:2;right:8px;top:8px;width:46px;height:46px;border:1px solid rgba(255,255,255,.35);border-radius:999px;background:rgba(20,18,15,.72);color:#fff;font-size:26px;line-height:1;display:grid;place-items:center;backdrop-filter:blur(8px)}
@media(max-width:720px){.taxonomyHome,.taxonomyCategory{padding:16px 12px 24px}.taxonomyGrid{grid-template-columns:1fr;gap:10px}.taxonomyMaster{min-height:118px;border-radius:15px;padding:16px 16px 21px;box-shadow:none}.taxonomyMaster:after{height:8px}.taxonomyMaster h2{margin:18px 0 4px;font-size:24px}.taxonomyCount{right:14px;top:14px;height:36px;min-width:36px}.taxonomyCategoryHead{align-items:center}.taxonomyCategoryHead h1{font-size:30px}.taxonomyCategory .grid{grid-template-columns:1fr}.recipeCard:after{height:7px}.taxonomyImageShade{padding:10px}.taxonomyImageViewer{width:100%;height:calc(100dvh - 20px)}.taxonomyImageViewer img{max-width:100%;max-height:88dvh;border-radius:14px}.taxonomyImageClose{right:6px;top:max(6px,env(safe-area-inset-top));width:44px;height:44px}}
`;
document.head.appendChild(style);
const lang=()=>document.documentElement.lang==='en'?'en':'es';
const tr=(es,en)=>lang()==='en'?en:es;
const text=(o,enKey,esKey)=>lang()==='en'?(o?.[enKey]||o?.[esKey]||''):(o?.[esKey]||o?.[enKey]||'');
const img=x=>x&&(x.url||x.image?.url||x.src)||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function activeRecipes(){return (DATA.recipes||[]).filter(r=>r.active!==false).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0))}
function activeProducts(){return (DATA.ingredients||[]).filter(i=>i.active!==false).sort((a,b)=>text(a,'nameEn','nameEs').localeCompare(text(b,'nameEn','nameEs')))}
function captureCards(){const cards=[...view.querySelectorAll('.recipeCard[data-r]')];if(!cards.length)return false;state.nativeCards={dish:[],prep:[]};cards.forEach(card=>{(card.classList.contains('cardDish')?state.nativeCards.dish:state.nativeCards.prep).push(card)});return true}
function syncBack(){if(state.productModal||state.mode!=='root')back.classList.remove('hidden');else if(!view.querySelector('.recipeView'))back.classList.add('hidden')}
function renderRoot(){state.applying=true;const dishes=activeRecipes().filter(r=>String(r.recipeType).toUpperCase()==='DISH').length,preps=activeRecipes().filter(r=>String(r.recipeType).toUpperCase()!=='DISH').length,products=activeProducts().length;view.innerHTML=`<div class="homeView taxonomyHome" data-taxonomy-view="root"><div class="taxonomyIntro"><h1 class="title">${esc(tr('Recetario dinámico','Dynamic recipe book'))}</h1><p class="subtitle">${esc(tr('Platos, preparaciones y productos organizados por categoría.','Dishes, preparations and products organized by category.'))}</p></div><div class="taxonomyGrid"><button class="taxonomyMaster dish" data-taxonomy-open="dish"><span class="taxonomyLabel">${esc(tr('Platos','Dishes'))}</span><span class="taxonomyCount">${dishes}</span><h2>${esc(tr('Platos','Dishes'))}</h2><p>${esc(tr('Recetas finales listas para servicio.','Final recipes ready for service.'))}</p></button><button class="taxonomyMaster prep" data-taxonomy-open="prep"><span class="taxonomyLabel">${esc(tr('Preparaciones','Preparations'))}</span><span class="taxonomyCount">${preps}</span><h2>${esc(tr('Preparaciones','Preparations'))}</h2><p>${esc(tr('Subrecetas y elaboraciones reutilizables.','Reusable subrecipes and preparations.'))}</p></button><button class="taxonomyMaster product" data-taxonomy-open="product"><span class="taxonomyLabel">${esc(tr('Productos','Products'))}</span><span class="taxonomyCount">${products}</span><h2>${esc(tr('Productos','Products'))}</h2><p>${esc(tr('Ingredientes y productos base.','Ingredients and base products.'))}</p></button></div></div>`;view.querySelectorAll('[data-taxonomy-open]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.taxonomyOpen;renderCategory()});syncBack();state.applying=false}
function productCard(p){const u=img(p.baseImage),name=text(p,'nameEn','nameEs');if(u)return `<button class="card recipeCard cardProduct taxonomyProductCard" data-product-id="${esc(p._id)}" aria-label="${esc(tr('Ver foto de ','View photo of ')+name)}"><div class="thumb"><img src="${esc(u)}" alt="${esc(name)}"></div><div class="meta"><span class="tag tagProduct">${esc(tr('Productos','Products'))}</span><h3>${esc(name)}</h3><span class="muted">${esc(tr('Producto base','Base product'))}</span></div></button>`;return `<article class="card recipeCard cardProduct taxonomyProductCard taxonomyNoPhoto"><div class="thumb"><span class="muted">${esc(tr('Sin foto','No photo'))}</span></div><div class="meta"><span class="tag tagProduct">${esc(tr('Productos','Products'))}</span><h3>${esc(name)}</h3><span class="muted">${esc(tr('Producto base','Base product'))}</span></div></article>`}
function renderCategory(){state.applying=true;const mode=state.mode,label=mode==='dish'?tr('Platos','Dishes'):mode==='prep'?tr('Preparaciones','Preparations'):tr('Productos','Products'),items=mode==='product'?activeProducts():(mode==='dish'?state.nativeCards.dish:state.nativeCards.prep);view.innerHTML=`<div class="homeView taxonomyCategory" data-taxonomy-view="${mode}"><div class="taxonomyCategoryHead"><div><h1>${esc(label)}</h1><p>${esc(tr(`${items.length} elementos`,` ${items.length} items`).trim())}</p></div><button class="taxonomyBackHint" data-tax-root>← ${esc(tr('Categorías','Categories'))}</button></div><input class="search" data-tax-search placeholder="${esc(tr('Buscar…','Search…'))}"><div class="grid" data-tax-grid></div></div>`;const grid=view.querySelector('[data-tax-grid]');if(mode==='product'){grid.innerHTML=items.map(productCard).join('');grid.querySelectorAll('[data-product-id]').forEach(b=>b.onclick=()=>openProductImage(b.dataset.productId))}else items.forEach(card=>grid.appendChild(card));view.querySelector('[data-tax-root]').onclick=()=>{state.mode='root';renderRoot()};const q=view.querySelector('[data-tax-search]');q.oninput=()=>{const needle=q.value.trim().toLowerCase();[...grid.children].forEach(card=>{card.style.display=!needle||card.textContent.toLowerCase().includes(needle)?'':'none'})};syncBack();state.applying=false}
function openProductImage(id){const p=activeProducts().find(x=>x._id===id);if(!p)return;const u=img(p.baseImage);if(!u)return;const name=text(p,'nameEn','nameEs');state.productModal=true;syncBack();modal.innerHTML=`<div class="taxonomyImageShade" id="taxonomyShade" role="dialog" aria-modal="true" aria-label="${esc(name)}"><div class="taxonomyImageViewer"><img src="${esc(u)}" alt="${esc(name)}"><button id="taxonomyClose" class="taxonomyImageClose" aria-label="${esc(tr('Cerrar','Close'))}">×</button></div></div>`;const close=()=>{state.productModal=false;modal.innerHTML='';syncBack()};document.getElementById('taxonomyClose').onclick=close;document.getElementById('taxonomyShade').onclick=e=>{if(e.target.id==='taxonomyShade')close()};state.closeProduct=close}
function apply(){if(state.applying)return;if(view.querySelector('.recipeView')){syncBack();return}const homeView=view.querySelector('.homeView');if(!homeView)return;const ownMode=homeView.getAttribute('data-taxonomy-view');if(ownMode===state.mode){syncBack();return}if(!ownMode)captureCards();if(state.mode==='root')renderRoot();else renderCategory()}
back.addEventListener('click',e=>{if(state.productModal){e.preventDefault();e.stopImmediatePropagation();state.closeProduct?.();return}if(view.querySelector('[data-taxonomy-view]')&&state.mode!=='root'){e.preventDefault();e.stopImmediatePropagation();state.mode='root';renderRoot()}},true);
home.addEventListener('click',()=>{state.mode='root';if(state.productModal)state.closeProduct?.()},true);
const observer=new MutationObserver(()=>{clearTimeout(state.timer);state.timer=setTimeout(apply,0)});observer.observe(view,{childList:true,subtree:false});
setTimeout(apply,0);
})();