(()=>{'use strict';
if(window.__NEXO_TAXONOMY_V3__)return;window.__NEXO_TAXONOMY_V3__=true;
const DATA=window.__NEXO_DM_DATA__||{recipes:[],ingredients:[],preparations:[]};
const view=document.getElementById('view'),back=document.getElementById('back'),home=document.getElementById('home'),modal=document.getElementById('modal');
if(!view||!back||!home||!modal)return;
const state={mode:'root',nativeCards:{dish:[],prep:[]},productModal:false,applying:false};
const style=document.createElement('style');style.id='nexo-taxonomy-v3-style';style.textContent=`
.recipeCard:before{display:none!important}.recipeCard{appearance:none!important;-webkit-appearance:none!important;position:relative!important;border-top:1px solid var(--line)!important}.recipeCard:after{content:"";position:absolute;z-index:4;left:0;right:0;bottom:0;height:9px;background:var(--product)}.recipeCard.cardDish:after{background:var(--dish)}.recipeCard.cardPrep:after{background:var(--prep)}.recipeCard.cardProduct:after{background:var(--product)}.recipeCard .meta{padding-bottom:22px!important}
.taxonomyHome,.taxonomyCategory{padding:0}.taxonomyIntro{margin-bottom:18px}.taxonomyGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.taxonomyMaster{appearance:none;-webkit-appearance:none;position:relative;min-height:210px;border:1px solid var(--line);border-radius:18px;background:var(--panel);overflow:hidden;text-align:left;padding:24px 22px 28px;box-shadow:0 8px 24px rgba(25,20,14,.06);color:var(--ink)}.taxonomyMaster:after{content:"";position:absolute;left:0;right:0;bottom:0;height:11px}.taxonomyMaster.dish:after{background:var(--dish)}.taxonomyMaster.prep:after{background:var(--prep)}.taxonomyMaster.product:after{background:var(--product)}.taxonomyMaster .taxonomyLabel{display:inline-flex;padding:5px 9px;border:1px solid currentColor;border-radius:999px;font-size:11px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.taxonomyMaster.dish .taxonomyLabel{color:var(--dish)}.taxonomyMaster.prep .taxonomyLabel{color:var(--prep)}.taxonomyMaster.product .taxonomyLabel{color:var(--product)}.taxonomyMaster h2{margin:34px 0 6px;font-size:30px;letter-spacing:-.035em}.taxonomyMaster p{margin:0;color:var(--muted)}.taxonomyCount{position:absolute;right:20px;top:20px;display:grid;place-items:center;min-width:42px;height:42px;padding:0 10px;border-radius:999px;background:var(--bg);font-weight:900}.taxonomyCategoryHead{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:12px}.taxonomyCategoryHead h1{margin:0;font-size:clamp(30px,5vw,46px);letter-spacing:-.035em}.taxonomyCategoryHead p{margin:5px 0 0;color:var(--muted)}.taxonomyCategory .search{margin-bottom:15px}.taxonomyProductPrepGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-top:10px}.taxonomyProductPrep{border:1px solid var(--line);border-radius:14px;overflow:hidden;background:#fff}.taxonomyProductPrep .pic{aspect-ratio:4/3}.taxonomyProductPrepBody{padding:10px}.taxonomyProductPrepBody b{display:block}.taxonomySectionTitle{margin:18px 0 8px;font-size:15px}.taxonomyProductBase{border:1px solid var(--line);border-radius:16px;overflow:hidden;background:#fff}.taxonomyProductBase .pic{aspect-ratio:16/9}.taxonomyProductBaseBody{padding:12px}.taxonomyProductBaseBody b{display:block}.taxonomyBackHint{border:1px solid var(--line);background:#fff;border-radius:12px;padding:9px 12px;font-weight:800}
@media(max-width:720px){.taxonomyHome,.taxonomyCategory{padding:16px 12px 24px}.taxonomyGrid{grid-template-columns:1fr;gap:10px}.taxonomyMaster{min-height:118px;border-radius:15px;padding:16px 16px 21px;box-shadow:none}.taxonomyMaster:after{height:8px}.taxonomyMaster h2{margin:18px 0 4px;font-size:24px}.taxonomyCount{right:14px;top:14px;height:36px;min-width:36px}.taxonomyCategoryHead{align-items:center}.taxonomyCategoryHead h1{font-size:30px}.taxonomyCategory .grid{grid-template-columns:1fr}.recipeCard:after{height:7px}.taxonomyProductPrepGrid{grid-template-columns:1fr 1fr}}
`;
document.head.appendChild(style);
const lang=()=>document.documentElement.lang==='en'?'en':'es';
const tr=(es,en)=>lang()==='en'?en:es;
const text=(o,enKey,esKey)=>lang()==='en'?(o?.[enKey]||o?.[esKey]||''):(o?.[esKey]||o?.[enKey]||'');
const img=x=>x&&(x.url||x.image?.url||x.src)||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function activeRecipes(){return (DATA.recipes||[]).filter(r=>r.active!==false).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0))}
function activeProducts(){return (DATA.ingredients||[]).filter(i=>i.active!==false).sort((a,b)=>text(a,'nameEn','nameEs').localeCompare(text(b,'nameEn','nameEs')))}
function captureCards(){const cards=[...view.querySelectorAll('.recipeCard[data-r]')];if(!cards.length)return false;state.nativeCards={dish:[],prep:[]};cards.forEach(card=>{(card.classList.contains('cardDish')?state.nativeCards.dish:state.nativeCards.prep).push(card)});return true}
function syncBack(){if(state.productModal||state.mode!=='root')back.classList.remove('hidden');else if(!view.querySelector('.recipeView'))back.classList.add('hidden')}
function renderRoot(){state.applying=true;const dishes=activeRecipes().filter(r=>String(r.recipeType).toUpperCase()==='DISH').length,preps=activeRecipes().filter(r=>String(r.recipeType).toUpperCase()!=='DISH').length,products=activeProducts().length;view.innerHTML=`<div class="homeView taxonomyHome" data-taxonomy-view="root"><div class="taxonomyIntro"><h1 class="title">${esc(tr('Recetario dinámico','Dynamic recipe book'))}</h1><p class="subtitle">${esc(tr('Platos, preparaciones y productos organizados por categoría.','Dishes, preparations and products organized by category.'))}</p></div><div class="taxonomyGrid"><button class="taxonomyMaster dish" data-taxonomy-open="dish"><span class="taxonomyLabel">${esc(tr('Platos','Dishes'))}</span><span class="taxonomyCount">${dishes}</span><h2>${esc(tr('Platos','Dishes'))}</h2><p>${esc(tr('Recetas finales listas para servicio.','Final recipes ready for service.'))}</p></button><button class="taxonomyMaster prep" data-taxonomy-open="prep"><span class="taxonomyLabel">${esc(tr('Preparaciones','Preparations'))}</span><span class="taxonomyCount">${preps}</span><h2>${esc(tr('Preparaciones','Preparations'))}</h2><p>${esc(tr('Subrecetas y elaboraciones reutilizables.','Reusable subrecipes and preparations.'))}</p></button><button class="taxonomyMaster product" data-taxonomy-open="product"><span class="taxonomyLabel">${esc(tr('Productos','Products'))}</span><span class="taxonomyCount">${products}</span><h2>${esc(tr('Productos','Products'))}</h2><p>${esc(tr('Ingredientes y productos base.','Ingredients and base products.'))}</p></button></div></div>`;view.querySelectorAll('[data-taxonomy-open]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.taxonomyOpen;renderCategory()});syncBack();state.applying=false}
function productCard(p){const u=img(p.baseImage),name=text(p,'nameEn','nameEs');return `<button class="card recipeCard cardProduct taxonomyProductCard" data-product-id="${esc(p._id)}"><div class="thumb">${u?`<img src="${esc(u)}" alt="${esc(name)}">`:`<span class="muted">${esc(tr('Sin foto','No photo'))}</span>`}</div><div class="meta"><span class="tag tagProduct">${esc(tr('Productos','Products'))}</span><h3>${esc(name)}</h3><span class="muted">${esc(tr('Producto base','Base product'))}</span></div></button>`}
function renderCategory(){state.applying=true;const mode=state.mode,label=mode==='dish'?tr('Platos','Dishes'):mode==='prep'?tr('Preparaciones','Preparations'):tr('Productos','Products'),items=mode==='product'?activeProducts():(mode==='dish'?state.nativeCards.dish:state.nativeCards.prep);view.innerHTML=`<div class="homeView taxonomyCategory" data-taxonomy-view="${mode}"><div class="taxonomyCategoryHead"><div><h1>${esc(label)}</h1><p>${esc(tr(`${items.length} elementos`,` ${items.length} items`).trim())}</p></div><button class="taxonomyBackHint" data-tax-root>← ${esc(tr('Categorías','Categories'))}</button></div><input class="search" data-tax-search placeholder="${esc(tr('Buscar…','Search…'))}"><div class="grid" data-tax-grid></div></div>`;const grid=view.querySelector('[data-tax-grid]');if(mode==='product'){grid.innerHTML=items.map(productCard).join('');grid.querySelectorAll('[data-product-id]').forEach(b=>b.onclick=()=>openProduct(b.dataset.productId))}else items.forEach(card=>grid.appendChild(card));view.querySelector('[data-tax-root]').onclick=()=>{state.mode='root';renderRoot()};const q=view.querySelector('[data-tax-search]');q.oninput=()=>{const needle=q.value.trim().toLowerCase();[...grid.children].forEach(card=>{card.style.display=!needle||card.textContent.toLowerCase().includes(needle)?'':'none'})};syncBack();state.applying=false}
function openProduct(id){const p=activeProducts().find(x=>x._id===id);if(!p)return;state.productModal=true;syncBack();const name=text(p,'nameEn','nameEs'),u=img(p.baseImage),preps=(DATA.preparations||[]).filter(x=>x.ingredientId===id).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0));let prepHtml='';if(preps.length){prepHtml=`<h3 class="taxonomySectionTitle">${esc(tr('Preparaciones / cortes','Preparations / cuts'))}</h3><div class="taxonomyProductPrepGrid">${preps.map(x=>{const n=text(x,'nameEn','nameEs'),pi=img(x.image);return `<div class="taxonomyProductPrep"><div class="pic">${pi?`<img src="${esc(pi)}" alt="${esc(n)}">`:`<span class="muted">${esc(tr('Sin foto','No photo'))}</span>`}</div><div class="taxonomyProductPrepBody"><b>${esc(n)}</b></div></div>`}).join('')}</div>`}modal.innerHTML=`<div class="modalShade" id="taxonomyShade"><div class="modal"><div class="modalHead"><h2>${esc(name)}</h2><button id="taxonomyClose" class="icon">×</button></div><span class="tag tagProduct">${esc(tr('Producto','Product'))}</span><div class="taxonomyProductBase"><div class="pic">${u?`<img src="${esc(u)}" alt="${esc(name)}">`:`<span class="muted">${esc(tr('Sin foto','No photo'))}</span>`}</div><div class="taxonomyProductBaseBody"><b>${esc(name)}</b><span class="muted">${esc(tr('Producto base','Base product'))}</span></div></div>${prepHtml}</div></div>`;const close=()=>{state.productModal=false;modal.innerHTML='';syncBack()};document.getElementById('taxonomyClose').onclick=close;document.getElementById('taxonomyShade').onclick=e=>{if(e.target.id==='taxonomyShade')close()};state.closeProduct=close}
function apply(){if(state.applying)return;if(view.querySelector('.recipeView')){syncBack();return}const homeView=view.querySelector('.homeView');if(!homeView)return;const ownMode=homeView.getAttribute('data-taxonomy-view');if(ownMode===state.mode){syncBack();return}if(!ownMode)captureCards();if(state.mode==='root')renderRoot();else renderCategory()}
back.addEventListener('click',e=>{if(state.productModal){e.preventDefault();e.stopImmediatePropagation();state.closeProduct?.();return}if(view.querySelector('[data-taxonomy-view]')&&state.mode!=='root'){e.preventDefault();e.stopImmediatePropagation();state.mode='root';renderRoot()}},true);
home.addEventListener('click',()=>{state.mode='root';if(state.productModal)state.closeProduct?.()},true);
const observer=new MutationObserver(()=>{clearTimeout(state.timer);state.timer=setTimeout(apply,0)});observer.observe(view,{childList:true,subtree:false});
setTimeout(apply,0);
})();